[Config]
MinimumVersion=26~devel

[Distribution]
Distribution=fedora
Release=44

[Content]
Hostname=carinata-????

[Build]
ToolsTree=default
History=yes
CacheDirectory=mkosi.cache
Incremental=yes

[Validation]
SecureBoot=no
SignExpectedPcr=no

[Output]
ImageId=Carinata
OutputDirectory=mkosi.output
ManifestFormat=json
Output=%i_%v_%a

