[main]
exclude=abrt-cli appstream-data chrony cronie deltarpm dracut-config-rescue grubby initial-setup* iptstate kernel-debug* mako mcelog mesa-va-drivers mtr noopenh264 PackageKit PackageKit-glib pinfo plocate psacct qemu-user-static realmd rsyslog* setroubleshoot setroubleshoot-plugins setroubleshoot-server sssd* systemd-networkd
