[Match]
Distribution=fedora

[Distribution]
Repositories=docker-ce-stable

[Content]
WithRecommends=false
WithDocs=false
Packages=
	cloud-init
	qemu-guest-agent
	rsync
	docker-ce
	docker-ce-cli
	docker-buildx-plugin
	containerd.io

